services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ${HOME}/.codex/auth.json:/home/node/.codex/auth.json:ro
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity